# Generated by Django 3.2 on 2021-08-18 22:01

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('authorization', '0002_alter_userprofile_notification_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
